import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  philosophersSidebar: [{type: 'autogenerated', dirName: '.', exclude: ['**/CLAUDE.md']}],
};

export default sidebars;
